### ISSUE TITLE
Icons verhalten sich seltsam.

### ISSUE THREAD

**Issue by simonszu** [fabianonline/geotweeter#20]
Ich hab gerade eine eigene Instanz vom GT aufgesetzt. Die .htaccess habe ich im großen und ganzen so gelassen, lediglich eine Zugriffskontrolle per htpasswd davor gedengelt. 
Nun ist es aber offenbar so, dass da irgendwas mit den Icons nicht funktioniert. 

Ein Pfad a la http://geotweeter.simonszu.de/icons/accept.png liefert ein 404.
Der Ordner existiert natürlich, und hat ein a+rx und die Dateien da drin ein a+r chmod.

Interessanterweise ist zB accept.png unter http://geotweeter.simonszu.de/icons/ auch nicht zu sehen, obwohl es in meinem Dateisystem vorhanden ist. 

Was ebenfalls äußerst interessant ist, dass die Dateien im Dateisystem einen last-modified Timestamp vom 20.2.2013 haben, allerdings zeigt der Apache einen last-modified von 2004-2008 an, sowie eine README.html, die in dem Ordner allerdings nicht vorhanden ist. 

Weißt du, was da los ist?

**Comment by fabianonline** [comment]
Das scheint ein anderer Ordner zu sein - sämtliche Bilder in dem Ordner (über den Webserver gesehen) gehören nicht zu den Icons, die da eigentlich sein sollten.

Kann es sein, dass da irgendein Teil der Apache-Konfig zwischenfunkt? IIRC nutzt der Apache z.B. ein Ordner "/icons", um die Bilder für die Verzeichnislistings anzuzeigen... Schau da vielleicht mal nach.

**Comment by simonszu** [comment]
Hm. Allerdings. Siehe auch hier: http://www.electrictoolbox.com/apache-icons-directory/

Ich kommentiere den Alias mal aus, aber falls du maximale Portabilität auf Debiankisten haben willst, würd ich an deiner Stelle das /icons umbenennen.
